### ISSUE TITLE
Password for hash code 6x4 decimal digits is missing

### ISSUE THREAD

**Issue by gitauto** [bacher09/pwgen-for-bios#14]
How to get password for hash code 6x4 decimal digits?

**Comment by qasimtoep** [comment]
Take a look at ebay ;-)

**Comment by DevHendrik** [comment]
Hi,
is there a solution for this? I checkes the python file from
http://dogber1.blogspot.com/2009/05/table-of-reverse-engineered-bios.html
File: http://sites.google.com/site/dogber1/blag/pwgen-fsi-6x4dec.py
I tried to port it into python 3.6.5 but due to my limited skills I'm having problems.
Does anybody have a source version working with 3.6.5?

Any help would be apreciated!

**Comment by kamazoy** [comment]
Just download a copy of Python 2.7 - works fine, I just tried it, gave me the master password within seconds

**Comment by bacher09** [comment]
Done in fd33defb36df532bf04da60b86399b12aa242a34.
