### ISSUE TITLE
HP password failed

### ISSUE THREAD

**Issue by TOTOleHero** [bacher09/pwgen-for-bios#31]
Hello,

I try lock code : "i 68354049"

The result is : "hp_mini : yundefinedgufqv1vo" the "undefined" is not a code. I think the pb come from the space character.

Could you help me ?

Thank you

**Comment by Crissstian** [comment]
Hi if you have resolved please, contact me i have the same problem and i don't know how resolve it, please

**Comment by bacher09** [comment]
Hi, thank you for filling report. Both tables for HP mini have no [corresponding code](https://github.com/bacher09/pwgen-for-bios/blob/typescript/scripts/decrypt_bios.ts#L128) for space. You can try to brute force this code, justtry all possibly symbols instead of `undefined`. It might be a tedious, but this may work.

**Comment by bacher09** [comment]
I'm closing this issue since latest master code will not calculate HP password for serial with space. And it seems that space is incorect input for HP unlock code.

Please reopen it if you firmware produced unlock code with space.
