### ISSUE TITLE
Updating Insyde H20 to 10 characteres

### ISSUE THREAD

**Issue by OtavioLara** [bacher09/pwgen-for-bios#56]
I'm trying to update your keygen for Insyde H20 bios because I lost mine password and it is a 10 characteres password.
First I successfully converted your code from TypeScript to Python, after that I tried to use 10 chrarcteres rather than 8, but the problem is the "salt" string: `const salt = "Iou|hj&Z";`

- How did you get this pattern?
- What shoud be the pattern to 10 characters?

Link to the file: [inside.ts](https://github.com/bacher09/pwgen-for-bios/blob/master/src/keygen/insyde.ts)

**Comment by bacher09** [comment]
It isn't matter how long was your original password was, if your firmware is using same algorithm it will accept password generated by software. In fact, for many different firmware it possible to generate multiple passwords that will be valid at the same time, this happens because of hash collisions.
But if your hash code (generated code) have different length, then most likely it will be using another algorithm.

> How did you get this pattern?

I didn't get this pattern, algorithm for Insyde H20 was researched by [dogber1](http://dogber1.blogspot.com/2009/05/table-of-reverse-engineered-bios.html). You can check his [python script](https://github.com/dogbert/bios-pwgen/blob/master/pwgen-insyde.py).

This information is collected by process called [reverse engineering](https://en.wikipedia.org/wiki/Reverse_engineering). First you usually need to get firmware blob, maybe read it from hardware or maybe it possible to download it from manufacturer website. Also, firmware blob usually contains multiple different sections and you need find and extract these that are used for code calculation. One of most popular binary analyzers for section extraction is [binwalk](https://github.com/ReFirmLabs/binwalk), but there is also many others. Also, sometimes, you will need to make your own, cause others will not work for you.  Then, it possible to inspect these files with disassembling/decompiling software, like [radare2](https://en.wikipedia.org/wiki/Radare2) or [IDA](https://en.wikipedia.org/wiki/Interactive_Disassembler). By inspecting disassembled code it possible to reconstruct code that was used to calculate hash and create algorithm that will be reverse or least will find some collision.

Also, I'd say that this description is very basic.

> What shoud be the pattern to 10 characters?

What do you mean ? Did you mean what algorithm is used for 10 digits hash code in your firmware ?
I have no idea.
